# Generated by Django 2.2.9 on 2020-01-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('zipcode', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=128)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Vendor')),
            ],
        ),
    ]
