# Generated by Django 2.2.9 on 2020-01-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('descr', models.CharField(max_length=256)),
                ('oid', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('networkType', models.PositiveIntegerField(default=1)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTypeFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=16)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.DeviceType')),
            ],
        ),
    ]
