# Generated by Django 2.2.9 on 2020-01-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_devicetype_devicetypeflags'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='config',
            field=models.PositiveIntegerField(choices=[(1, 'Text'), (2, 'Binary')], default=1),
        ),
    ]
