# Generated by Django 2.2.9 on 2020-01-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_devicetype_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetype',
            old_name='config',
            new_name='configType',
        ),
    ]
