# Generated by Django 2.2.9 on 2020-01-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20200101_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('deviceType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.DeviceType')),
            ],
        ),
    ]
