# Generated by Django 2.2.9 on 2020-01-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20200101_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('telnet_user', models.CharField(max_length=32)),
                ('telnet_pass', models.CharField(max_length=64)),
                ('snmp_ro', models.CharField(max_length=64)),
                ('snmp_rw', models.CharField(max_length=64)),
                ('securityName', models.CharField(max_length=64)),
                ('authProtocol', models.CharField(choices=[('sha', 'SHA'), ('md5', 'MD5')], default='md5', max_length=3)),
                ('authKey', models.CharField(max_length=64)),
                ('privProtocol', models.CharField(choices=[('des', 'DES'), ('aes', 'AES')], default='aes', max_length=3)),
                ('privKey', models.CharField(max_length=64)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='EngineID',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='device',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='doesSsh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='doesTelnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='osType',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='osVersion',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='snmpPort',
            field=models.PositiveIntegerField(default=161),
        ),
        migrations.AddField(
            model_name='device',
            name='sysDescr',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='device',
            name='sysLocation',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='device',
            name='sysObjectID',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.CreateModel(
            name='DeviceSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telnet_user', models.CharField(max_length=32)),
                ('telnet_pass', models.CharField(max_length=64)),
                ('snmp_ro', models.CharField(max_length=64)),
                ('snmp_rw', models.CharField(max_length=64)),
                ('securityName', models.CharField(max_length=64)),
                ('authProtocol', models.CharField(choices=[('sha', 'SHA'), ('md5', 'MD5')], default='md5', max_length=3)),
                ('authKey', models.CharField(max_length=64)),
                ('privProtocol', models.CharField(choices=[('des', 'DES'), ('aes', 'AES')], default='aes', max_length=3)),
                ('privKey', models.CharField(max_length=64)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Device')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icmpError', models.BooleanField(default=False)),
                ('snmpError', models.BooleanField(default=False)),
                ('configError', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Device')),
            ],
        ),
    ]
