# Generated by Django 2.2.9 on 2020-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20200102_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='osType',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='osVersion',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
